# Dockerfile.sitemap
FROM node:20-alpine

WORKDIR /app

# Package fayllarini nusxalash
COPY package*.json ./

# BARCHA dependensiyalarni o'rnatish
RUN npm ci

# Source kodlarni nusxalash
COPY . .

# Sitemap generator skriptini ishga tushirish
CMD ["npm", "run", "sitemap"]
