version: '3.8'

services:
  sitemap:
    build: .
    container_name: shingeki-sitemap
    ports:
      - "1111:1111"
    environment:
      - API_URL=https://bk.afd-platform.uz/afd-platform/backend/urls/tnall-animes/?no_pagination=true
      - PORT=1111
    restart: unless-stopped
